app/blueprints/core/routes.py
from flask import request, render_template, Blueprint  # noqa: F401
import requests
from flask import jsonify, url_for, redirect
import os
from dotenv import load_dotenv
import json
from werkzeug.utils import secure_filename
import markdown2
from flask_ckeditor.utils import cleanify

from app.blueprints.core.models import NoCoRecipes
from icecream import ic

core = Blueprint("core", __name__, template_folder='templates')
 

# Define a base URL and API token for NocoDB
# Load the .env file
load_dotenv()

NOCO_DB_BASE_URL = os.getenv("NOCO_DB_BASE_URL")
NOCO_DB_TABLE_ID = os.getenv("NOCO_DB_RECIPES_TABLE_ID")  
NOCO_DB_API_TOKEN = os.getenv("NOCO_DB_API_TOKEN")  

headers = {
    "xc-token": NOCO_DB_API_TOKEN
}
ic(NOCO_DB_BASE_URL, NOCO_DB_TABLE_ID, NOCO_DB_API_TOKEN, headers)

def get_recipe_by_id(recipe_id):
    """Fetch a recipe by ID from the NoCoDB API."""
    # Use the table ID in the URL
    url = f"{NOCO_DB_BASE_URL}/tables/{NOCO_DB_TABLE_ID}/records/{recipe_id}"
    response = requests.get(url, headers=headers)
    
    if response.status_code == 200:
        data = response.json()
        return NoCoRecipes.from_api_data(data)
    else:
        print(f"Failed to fetch recipe with ID {recipe_id}: {response.status_code}")
        return None

def save_recipe(recipe):
    """
    Save the updated recipe data to the NoCoDB API.
    
    Parameters:
        recipe (NoCoRecipes): The recipe object containing updated data.
    
    Returns:
        bool: True if the update was successful, False otherwise.
    """
    # Use the table's records endpoint without specifying the ID in the URL
    url = f"{NOCO_DB_BASE_URL}/tables/{NOCO_DB_TABLE_ID}/records"
    headers = {
        "xc-token": NOCO_DB_API_TOKEN,
        "Content-Type": "application/json"
    }
    print('Saving recipe to NocoDB...')
    # Convert the recipe object to a dictionary format and include the ID
    data = recipe.to_dict()
    data['Id'] = recipe.Id  # Include the ID in the request body
    
    # Send the PATCH request to update the recipe
    response = requests.patch(url, headers=headers, json=data)
    
    if response.status_code == 200:
        print("Recipe updated successfully.")
        return None
    else:
        print(f"Failed to update recipe with ID {recipe.Id}: {response.status_code} - {response.text}")
        return None

# Upload file to storage and retrieve attachment metadata
def upload_file_to_storage(file_path):
    target_path = f"download/noco/{NOCO_DB_TABLE_ID}/{secure_filename(os.path.basename(file_path))}"
    url = f"{NOCO_DB_BASE_URL}/storage/upload?path={target_path}"
    filename = secure_filename(file_path.split("/")[-1])
    file_size = os.path.getsize(file_path)
    mime_type = "image/jpeg"  # Adjust MIME type as needed

    with open(file_path, 'rb') as file:
        files = {
            "mimetype": (None, mime_type),
            "path": (None, target_path),
            "size": (None, str(file_size)),
            "title": (None, filename),
            "file": (filename, file, mime_type)
        }
        response = requests.post(url, headers=headers, files=files)
    
    if response.status_code == 200:
        print("File uploaded successfully.")
        return response.json()
    else:
        print(f"File upload failed: {response.status_code} - {response.text}")
        return None

# Update the record with the attachment metadata
def update_record_with_attachment(record_id, attachment_metadata):
    # If metadata is a list, get the first item (assuming only one attachment)
    if isinstance(attachment_metadata, list):
        attachment_metadata = attachment_metadata[0]

    # Prepare the attachment JSON
    attachment_json = {
        "path": attachment_metadata.get("path"),
        "title": attachment_metadata.get("title"),
        "mimetype": attachment_metadata.get("mimetype"),
        "size": attachment_metadata.get("size"),
        "signedPath": attachment_metadata.get("signedPath", ""),
    }
    if "id" in attachment_metadata:
        attachment_json["id"] = attachment_metadata["id"]
    
    # The request URL without a specific record ID
    url = f"{NOCO_DB_BASE_URL}/tables/{NOCO_DB_TABLE_ID}/records"
    
    # Payload now includes the record ID in the body, along with the updated attachment data
    payload = {
        "Id": record_id,  # Including record ID in the payload
        "Photo": json.dumps([attachment_json])  # Assuming "Photo" is the attachment column
    }
    headers_with_content_type = {**headers, "Content-Type": "application/json"}

    # Send the PATCH request
    response = requests.patch(url, headers=headers_with_content_type, json=payload)
    
    if response.status_code == 200:
        print("Record updated successfully with attachment.")
        return response.json()
    else:
        print(f"Failed to update record: {response.status_code} - {response.text}")
        return None

@core.route('/')
def index():
    # Make a request to NocoDB to get all recipes
    url = f"{NOCO_DB_BASE_URL}/tables/{NOCO_DB_TABLE_ID}/records"
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        # Convert API data to NoCoShop instances
        data = response.json().get("list", [])
        recipes = [NoCoRecipes.from_api_data(item) for item in data]
        return render_template('core/index.html', recipes=recipes)
    else:
        ic(url, response)
        return jsonify({"error": "Failed to retrieve recipes", "status_code": response.status_code}), response.status_code
    

@core.route('/search', methods=['GET', 'POST'])
def search():
    # Get the 'search' query parameter from the request, split by whitespace to get each word
    query = request.args.get('search', '').strip()
    words = query.lower().split()  # Split by space and convert to lowercase for case-insensitive search
    
    # Fetch all recipes from NoCo DB (you may later optimize this if NoCo supports more advanced filtering)
    url = f"{NOCO_DB_BASE_URL}/tables/{NOCO_DB_TABLE_ID}/records"
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        data = response.json().get("list", [])
        recipes_data = [NoCoRecipes.from_api_data(item) for item in data]
        
        # Filter recipes: check if any word is in any relevant field
        if words:
            recipes = [
                recipe for recipe in recipes_data if all(
                    word in (recipe.Title or '').lower() or
                    word in (recipe.Meal or '').lower() or
                    word in (recipe.Core or '').lower() or
                    word in (recipe.Source or '').lower()
                    for word in words
                )
            ]
        else:
            recipes = recipes_data  # No search query, return all recipes

        return render_template('core/search.html', recipes=recipes, noco_db_url = NOCO_DB_BASE_URL)
    else:
        return jsonify({"error": "Failed to retrieve recipes", "status_code": response.status_code}), response.status_code

@core.route('/recipe/<int:Id>')
def recipe(Id):
    # Make a request to NocoDB to get the specific recipe by Id
    url = f"{NOCO_DB_BASE_URL}/tables/{NOCO_DB_TABLE_ID}/records/{Id}"
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        # Convert API data to a NoCoRecipe instance (or NoCoRecipe if different)
        data = response.json()
        recipe = NoCoRecipes.from_api_data(data)
        if recipe.Ingredients:
            ingredients_html = markdown2.markdown(recipe.Ingredients)
        else:
            ingredients_html = ""
        if recipe.Method:
            method_html = markdown2.markdown(recipe.Method)
        else:
            method_html = ""
        return render_template('core/recipe.html', recipe=recipe, ingredients_html=ingredients_html, method_html=method_html)
    else:
        return jsonify({"error": "Failed to retrieve recipe", "status_code": response.status_code}), response.status_code


@core.route('/edit_field/<int:recipe_id>/<field>', methods=['GET'])
def edit_field(recipe_id, field):
    # Retrieve the recipe based on `recipe_id`
    
    recipe = get_recipe_by_id(recipe_id)  
    print(recipe)
    current_value = getattr(recipe, field, "")
    print(current_value)
    
    # Render the editable field template with an input field
    return render_template('core/editable_field.html', field=field, recipe_id=recipe_id, current_value=current_value)

@core.route('/edit_rich_field/<int:recipe_id>/<field>', methods=['GET'])
def edit_rich_field(recipe_id, field):
    # Retrieve the recipe based on `recipe_id`
    recipe = get_recipe_by_id(recipe_id)  
    print(recipe)
    current_value = getattr(recipe, field, "")
    print(current_value)
    
    # Render the editable field template with an input field
    return render_template('core/editable_rich_field.html', field=field, recipe_id=recipe_id, current_value=current_value)


@core.route('/update_field/<int:recipe_id>/<field>', methods=['POST'])
def update_field(recipe_id, field):
    # Get the new value from the POST request
    new_value = request.form['value']
    
    # Retrieve and update the recipe in the database
    recipe = get_recipe_by_id(recipe_id)  # Replace with your own function to fetch the recipe
    setattr(recipe, field, new_value)  # Update the field
    save_recipe(recipe)  # Save the updated recipe to the database/API

    # Return the display field after updating
    return render_template('core/display_field.html', field=field, value=new_value, recipe_id=recipe_id)

@core.route('/update_rich_field/<int:recipe_id>/<field>', methods=['POST'])
def update_rich_field(recipe_id, field):
    # Get the new value from the POST request
    new_value = cleanify(request.form['value'])
    
    # Retrieve and update the recipe in the database
    recipe = get_recipe_by_id(recipe_id)  # Replace with your own function to fetch the recipe

app/blueprints/core/templates/core/display_field.html
<span hx-get="{{ url_for('core.edit_field', field=field, recipe_id=recipe_id) }}" 
      hx-trigger="click" 
      hx-target="#{{ field | lower }}-field" 
      hx-swap="outerHTML" 
      id="{{ field | lower }}-field">
    {{ value }}
</span>

app/blueprints/core/templates/core/display_rich_field.html
<span hx-get="{{ url_for('core.edit_rich_field', field=field, recipe_id=recipe_id) }}" 
      hx-trigger="click" 
      hx-target="#{{ field | lower }}-field" 
      hx-swap="outerHTML" 
      id="{{ field | lower }}-field">
    {{ value | safe }}
</span>

app/blueprints/core/templates/core/editable_field.html
<form hx-post="{{ url_for('core.update_field', recipe_id=recipe_id, field=field) }}" 
      hx-target="#{{ field | lower }}-field" 
      hx-swap="outerHTML"
      id="{{ field | lower }}-field">
      
    <input type="text" name="value" value="{{ current_value }}" class="form-control mb-2" autofocus>
    
    <div class="d-flex justify-content-between">
      <!-- Update Button with Bootstrap Success Color -->
      <button type="submit" class="btn btn-success me-2">Update</button>
      
      <!-- Cancel Button to revert back to display mode -->
      <button type="button" class="btn btn-primary"
              hx-get="{{ url_for('core.display_field', recipe_id=recipe_id, field=field) }}" 
              hx-target="#{{ field | lower }}-field" 
              hx-swap="outerHTML"
              hx-indicator="#spinner">
          Cancel
      </button>
      <div class=" htmx-indicator" id="spinner">
        <div class="spinner-border text-primary" role="status">
          <span class="sr-only"></span>
        </div>
      </div>
    </div>
</form>

app/blueprints/core/templates/core/editable_rich_field.html
<form class="w-100"

      hx-post="{{ url_for('core.update_rich_field', recipe_id=recipe_id, field=field) }}" 
      hx-target="#{{ field | lower }}-field" 
      hx-swap="outerHTML"
      id="{{ field | lower }}-field"
      hx-on="htmx:configRequest: console.log('HTMX request:', event.detail);">
      {{ ckeditor.create('value', value=current_value) }}
    
    <div class="d-flex justify-content-between">
      <!-- Update Button with Bootstrap Success Color -->
      <button type="submit" class="btn btn-success me-2">Update</button>
      
      <!-- Cancel Button to revert back to display mode -->
      <button type="button" class="btn btn-primary"
              hx-get="{{ url_for('core.display_rich_field', recipe_id=recipe_id, field=field) }}" 
              hx-target="#{{ field | lower }}-field" 
              hx-swap="outerHTML"
              hx-indicator="#spinner">
          Cancel
      </button>
      <div class=" htmx-indicator" id="spinner">
        <div class="spinner-border text-primary" role="status">
          <span class="sr-only"></span>
        </div>
      </div>
    </div>
</form>

app/blueprints/core/templates/core/index copy.html
<!-- List of and search for all recipes -->
{% extends "base.html" %}
{% block title %}Recipes{% endblock %}

{% block content %}
<section class="hero align-items-center justify-content-center d-flex flex-column"
    style="background-image: url('https://images.unsplash.com/photo-1515665966984-831e4cd20f96?q=80&w=2680&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');
        background-size: cover; background-position: center; background-repeat: no-repeat;
        height: 300px; width: 100%; position: relative;
        display: flex; justify-content: center; align-items: center;
        color: white; text-shadow: 2px 2px 8px rgba(0, 0, 0, 0.7);
        background-color: rgba(0, 0, 0, 0.25); 
        background-blend-mode: darken;
        margin-left: 0; /* This ensures it doesn’t overlap with the sidebar */
        ">
    <!-- Hero Text (with shadow for readability) -->
    <div class="mt-auto mb-auto col-10" style="padding-top: 30px;">
        <h1 class="display-1 text-white mb-4 text-center" style="text-shadow: 2px 2px 8px rgba(0, 0, 0, 0.7);">
            Recipes
        </h1>
        <!-- Sticky Search Bar -->
        <div id="search-bar" class=" col-md-6 col-sm-10 d-flex flex-column justify-content-center bg-white rounded shadow-sm mt-4 mx-auto">
            <input 
                type="text" 
                class="form-control"
                name="search" 
                placeholder="Search recipe name, type, or source" 
                value="{{ text or '' }}"
                hx-get="{{ url_for('core.search') }}"
                hx-trigger="keyup delay:500ms changed"
                hx-target="#recipes-list"
                hx-swap="innerHTML"
                hx-indicator="#loading-indicator">
        </div>
    </div>
</section>
<!-- List of and search for all recipes -->

<!-- Scrollable Recipe List Container -->
<div class="container py-3 ps-4">
    <div class="row">
        <div class="col-12">
            <!-- Scrollable div with a maximum height -->
            <div style="max-height: 500px; overflow-y: auto; padding-right: 15px;">
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 justify-content-center" id="recipes-list">
                    <!-- HTMX will replace this content with filtered recipes -->
                    {% for recipe in recipes %}
                    <div class="col d-flex justify-content-center shop-card">
                        <div class="card h-100 w-100">
                            <div class="ratio ratio-16x9">
                                {% if recipe.Photo and recipe.Photo[0].signedPath %}
                                    <img src="http://192.168.178.70:8080/{{ recipe.Photo[0].signedPath }}" 
                                         class="card-img-top img-fluid" style="object-fit: cover;" alt="{{ recipe.Title }}">
                                {% else %}
                                    <img src="https://images.unsplash.com/photo-1509358271058-acd22cc93898?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" 
                                         class="card-img-top img-fluid" style="object-fit: cover;" alt="{{ recipe.Title }}">
                                {% endif %}
                            </div>
                            <div class="card-body row d-flex justify-content-between">
                                <div class="col d-flex flex-column justify-content-between col-9">
                                    <h5 class="card-title">{{ recipe.Title }}</h5>
                                    <p class="card-text align-items-end">
                                        {{ recipe.Meal }}, 
                                        {{ recipe.Core }} <br>
                                        {{ recipe.Source | safe }}
                                    </p>
                                </div>
                                <div class="col d-flex justify-content-end align-self-end col-3 mt-auto">
                                    <a href="{{ url_for('core.recipe', Id=recipe.Id) }}" class="btn btn-primary d-flex justify-content-center align-items-center" style="height: 40px;">View</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/blueprints/core/templates/core/index.html
<!-- List of and search for all recipes -->
{% extends "base.html" %}
{% block title %}Recipes{% endblock %}

{% block content %}
<section class="hero align-items-center justify-content-center d-flex flex-column border-5 border-bottom border-white"
    style="background-image: url('https://images.unsplash.com/photo-1515665966984-831e4cd20f96?q=80&w=2680&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');
        background-size: cover; background-position: center; background-repeat: no-repeat;
        height: 300px; width: 100%; position: relative;
        display: flex; justify-content: center; align-items: center;
        color: white; text-shadow: 2px 2px 8px rgba(0, 0, 0, 0.7);
        background-color: rgba(0, 0, 0, 0.25); 
        background-blend-mode: darken;
        margin-left: 0; /* This ensures it doesn’t overlap with the sidebar */
        ">
    <!-- Hero Text (with shadow for readability) -->
    <div class="mt-auto mb-auto col-10" style="padding-top: 30px;">
        <h1 class="display-1 text-white mb-4 text-center" style="text-shadow: 2px 2px 8px rgba(0, 0, 0, 0.7);">
            Recipes
        </h1>
        <!-- Sticky Search Bar -->
        <div id="search-bar" class=" col-md-6 col-sm-10 d-flex flex-column justify-content-center bg-white rounded shadow-sm mt-4 mx-auto">
            <input 
                type="text" 
                class="form-control"
                name="search" 
                placeholder="Search recipe name, type, or source" 
                value="{{ text or '' }}"
                hx-get="{{ url_for('core.search') }}"
                hx-trigger="keyup delay:500ms changed"
                hx-target="#recipes-list"
                hx-swap="innerHTML"
                hx-indicator="#loading-indicator">
        </div>
    </div>
</section>
<!-- List of and search for all recipes -->

<!-- Scrollable Recipe List Container -->
<div class="container py-3 ps-4" style="height: calc(100vh - 300px); overflow-y: auto;">
    <div class="row">
        <div class="col-12 col-md-auto">
            <!-- Scrollable div with a maximum height -->
            <div class="" style="padding-right: 15px; ">
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 justify-content-center" id="recipes-list">
                    <!-- HTMX will return blank search results on initial load, and then swap with filtered recipes on search -->
                    <div hx-get="{{ url_for('core.search') }}" hx-target="#recipes-list" hx-swap="innerHTML" hx-trigger="load"></div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/blueprints/core/templates/core/recipe.html
<!-- Show detail of an individual wine Recipes -->
{% extends "base.html" %}
{% block title %}Recipe{% endblock %}
{{ ckeditor.load() }}

{% block content %}
<!-- Full-Screen Loading Spinner Modal (initially hidden) -->
<div class="container my-5">
    <div class="profile-card">
        <!-- Profile Header with Editable Toggle Button -->
        <div class="profile-header d-flex justify-content-between align-items-center">
            <!-- Title Field -->
            <div id="title-field" class="d-flex justify-content-between align-items-center">
                <h2 class="editable-field">
                    {{ recipe.Title }}
                </h2>
                <button class="btn btn-sm hidden toggleable-button"
                        hx-get="{{ url_for('core.edit_field', recipe_id=recipe.Id, field='Title') }}"
                        hx-target="#title-field"
                        hx-swap="outerHTML">
                    <i class="bi bi-pencil"></i> <!-- Bootstrap pencil icon -->
                </button>
            </div>
        <!-- Edit Button -->
            <button class="btn btn-outline-primary btn-edit" id="toggle-edit" onclick="toggleButtons()">Edit</button>
        </div>
        
        <!-- Profile Body with Editable Details -->
        <div class="profile-body row">
            <!-- Recipe Details -->
            <div class="col-12 col-md-7">
                <div class="d-flex flex-column gap-3">
                    <!-- Editable Meal Field -->
                    <div class="icon-text d-flex align-items-start">
                        {% if recipe.Meal == "Brunch" %}
                            <i class="bi bi-sunrise-fill fs-3 me-2"></i>
                        {% elif recipe.Meal == "Lunch" %}
                            <i class="bi bi-sun-fill fs-3 me-2"></i>
                        {% elif recipe.Meal == "Dinner" %}
                            <i class="bi bi-sunset-fill fs-3 me-2"></i>
                        {% elif recipe.Meal == "BBQ" %}
                            <i class="bi bi-emoji-sunglasses-fill fs-3 me-2"></i>
                        {% endif %}
                        <span id="meal-field" class="fs-4 text-wrap">
                            <strong>Meal:</strong> {{ recipe.Meal or "N/A" }}
                        </span>
                        <button class="btn btn-sm hidden toggleable-button"
                                hx-get="{{ url_for('core.edit_field', recipe_id=recipe.Id, field='Meal') }}"
                                hx-target="#meal-field"
                                hx-swap="outerHTML">
                            <i class="bi bi-pencil"></i>
                        </button>
                    </div>
                    
                    <!-- Editable Core Field -->
                    <div class="icon-text d-flex align-items-start">
                        <i class="bi bi-egg-fill fs-3 me-2"></i>
                        <span id="core-field" class="fs-4 text-wrap">
                            <strong>Core:</strong> {{ recipe.Core or "N/A" }}
                        </span>
                        <button class="btn btn-sm hidden toggleable-button"
                                hx-get="{{ url_for('core.edit_field', recipe_id=recipe.Id, field='Core') }}"
                                hx-target="#core-field"
                                hx-swap="outerHTML">
                            <i class="bi bi-pencil"></i>
                        </button>
                    </div>
                    
                    <!-- Editable Source Field -->
                    <div class="icon-text d-flex align-items-start">
                        <i class="bi bi-person-lines-fill fs-3 me-2"></i>
                        <div class="d-flex flex-grow-1 align-items-center">
                            <span class="fs-4 text-wrap" style="word-break: break-word;">
                                <strong>Source:</strong>
                                <span id="source-field">
                                    {% if recipe.Source %}
                                        {% for word in recipe.Source.split() %}
                                            {% if word.startswith("http") %}
                                                <a href="{{ word }}" target="_blank" rel="noopener noreferrer" class="text-decoration-none">
                                                    Link
                                                </a>
                                            {% else %}
                                                {{ word }}
                                            {% endif %}
                                            {% if not loop.last %} {{ " " }} {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        No source available
                                    {% endif %}
                                </span>
                            </span>
                            
                            <!-- Edit Button with Icon -->
                            <button class="btn btn-sm ms-2 hidden toggleable-button"
                                    hx-get="{{ url_for('core.edit_field', field='Source', recipe_id=recipe.Id) }}"
                                    hx-target="#source-field"
                                    hx-swap="outerHTML">
                                <i class="bi bi-pencil"></i> <!-- Bootstrap pencil icon -->
                            </button>
                        </div>
                    </div>
                    <!-- Notes -->
                    <div class="icon-text d-flex align-items-start">
                        <i class="bi bi-bookmark-check-fill fs-3 me-2"></i>
                        <div class="d-flex flex-grow-1 align-items-center">
                                <span id="notes-field" class="fs-4 text-wrap">
                                    <strong>Notes</strong><br> {{ recipe.Notes or "N/A" }}
                                </span>
                                <button class="btn btn-sm hidden toggleable-button"
                                        hx-get="{{ url_for('core.edit_field', recipe_id=recipe.Id, field='Notes') }}"
                                        hx-target="#notes-field"
                                        hx-swap="outerHTML">
                                    <i class="bi bi-pencil"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Recipe Image -->
            <div class="col-12 col-md-5 mb-4">
                <!-- Photo Display Section -->
                <div id="photo-section">
                    {% if recipe.Photo and recipe.Photo[0].signedPath %}
                        <img src="http://192.168.178.70:8080/{{ recipe.Photo[0].signedPath }}" class="img-fluid rounded-3 mb-3" alt="{{ recipe.Title }}">
                    {% else %}
                        <img src="https://images.unsplash.com/photo-1509358271058-acd22cc93898?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" 
                            class="img-fluid rounded-3 mb-3" alt="{{ recipe.Title }}">
                    {% endif %}
                </div>

                <!-- Conditionally Display Photo Upload Button -->
                <div id="photo-upload-section" class="mt-3">
                    <button type="button" class="btn btn-primary hidden toggleable-button"
                            hx-get="{{ url_for('core.upload_photo_field', recipe_id=recipe.Id) }}" 
                            hx-target="#photo-upload-section" 
                            hx-swap="outerHTML">
                        Upload or Replace Photo
                    </button>
                </div>
            </div>

        </div>
        <!-- Recipe Ingredients -->
        <div class="profile-body pt-0 column">
            <div class="icon-text d-flex align-items-start">     
                <span class="fs-4 text-wrap w-100" style="word-break: break-word;">
                    <div class="pb-2">
                        <strong >Ingredients</strong>
                    </div>
                    <span id="ingredients-field">
                        {% if recipe.Ingredients %}
                            {{ ingredients_html | safe }}
                        {% else %}
                            No ingredients
                        {% endif %}
                    </span>
                </span>
                
                <!-- Edit Button with Icon -->
                <button class="btn btn-sm ms-2 hidden toggleable-button"
                        hx-get="{{ url_for('core.edit_rich_field', field='Ingredients', recipe_id=recipe.Id) }}"
                        hx-target="#ingredients-field"
                        hx-swap="outerHTML">
                    <i class="bi bi-pencil"></i> <!-- Bootstrap pencil icon -->
                </button>
            </div>

            <!-- Recipe Method -->
            <div class="icon-text d-flex align-items-start pt-2">     
                <span class="fs-4 text-wrap w-100" style="word-break: break-word;">
                    <div class="pb-2">
                        <strong >Method</strong>
                    </div>
                    <span id="method-field" style="padding-bottom: 10px;">
                        {% if recipe.Method %}
                            {{ method_html | safe }}
                        {% else %}
                            No Method
                        {% endif %}
                    </span>
                </span>
                
                <!-- Edit Button with Icon -->
                <button class="btn btn-sm ms-2 hidden toggleable-button"
                        hx-get="{{ url_for('core.edit_rich_field', field='Method', recipe_id=recipe.Id) }}"
                        hx-target="#method-field"
                        hx-swap="outerHTML">
                    <i class="bi bi-pencil"></i> <!-- Bootstrap pencil icon -->
                </button>
            </div>
        </div>
    </div>
</div>

<script>
    function toggleButtons() {
        // Toggle visibility of elements with the 'toggleable-button' class
        document.querySelectorAll('.toggleable-button').forEach(button => {
            button.classList.toggle('hidden');
        });
        
        // Get the edit button itself
        const editButton = document.getElementById("toggle-edit");

        // Toggle the 'active' class for color change
        editButton.classList.toggle("active");

        // Change text between "Edit" and "Done"
        editButton.textContent = editButton.classList.contains("active") ? "Done" : "Edit";
    }
</script>

<style>
    .hidden {
        display: none;
    }

   /* Initial red button styling */
   .btn-edit {
    background-color: #ff6b6b; /* Solid red background */
    color: white;
    border: none;
    padding: 8px 16px;
    font-weight: bold;
    transition: background-color 0.3s ease; /* Smooth transition */
}

/* Blue styling when in "Done" state */
.btn-edit.active {
    background-color: #0c1844; /* Solid blue background */
    color: white;
}

/* Optional: Adjust rounded corners if needed */
.btn-edit {
    border-radius: 8px; /* Rounded corners */
}

.ckeditor{
    width: 100%;
}
</style>


{% endblock %}